---
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # System logs
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log
          host: monitoring-host

  # Docker container logs
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log
          host: monitoring-host

    # Extract container name from log path
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            time: time
      - timestamp:
          source: time
          format: RFC3339Nano
      - output:
          source: output

  # Custom application logs (add your app log paths here)
  # - job_name: my-app
  #   static_configs:
  #     - targets:
  #         - localhost
  #       labels:
  #         job: my-app
  #         __path__: /path/to/your/app/logs/*.log
  #         host: monitoring-host
