---
global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@yourdomain.com'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/'

# Example email configuration (uncomment and configure as needed)
# - name: 'email-alerts'
#   email_configs:
#   - to: 'admin@yourdomain.com'
#     subject: 'Alert: {{ .GroupLabels.alertname }}'
#     body: |
#       {{ range .Alerts }}
#       Alert: {{ .Annotations.summary }}
#       Description: {{ .Annotations.description }}
#       {{ end }}

# Example Slack configuration (uncomment and configure as needed)
# - name: 'slack-alerts'
#   slack_configs:
#   - api_url: 'YOUR_SLACK_WEBHOOK_URL'
#     channel: '#alerts'
#     title: 'Alert: {{ .GroupLabels.alertname }}'
#     text: |
#       {{ range .Alerts }}
#       {{ .Annotations.summary }}
#       {{ .Annotations.description }}
#       {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
